In [59]:
import pandas as pd
import numpy as np

%precision 3
pd.set_option('precision', 3)

In [14]:
df = pd.read_csv('../data/data/ch2_scores_em.csv',index_col='生徒番号')

In [15]:
df

英語  数学
生徒番号        
1     42  65
2     69  80
3     56  63
4     41  63
5     57  76
6     48  60
7     65  81
8     49  66
9     65  78
10    58  82
11    70  94
12    47  75
13    51  70
14    64  77
15    62  84
16    70  84
17    71  82
18    68  85
19    73  90
20    37  70
21    65  78
22    65  93
23    61  77
24    52  88
25    57  82
26    57  76
27    75  87
28    61  84
29    47  77
30    54  82
31    66  91
32    54  75
33    54  76
34    42  78
35    37  57
36    79  89
37    56  83
38    62  69
39    62  86
40    55  81
41    63  81
42    57  80
43    57  79
44    67  87
45    55  84
46    45  71
47    66  80
48    55  77
49    64  83
50    66  88

In [16]:
df.shape

(50, 2)

In [17]:
df.head

<bound method NDFrame.head of       英語  数学
生徒番号        
1     42  65
2     69  80
3     56  63
4     41  63
5     57  76
6     48  60
7     65  81
8     49  66
9     65  78
10    58  82
11    70  94
12    47  75
13    51  70
14    64  77
15    62  84
16    70  84
17    71  82
18    68  85
19    73  90
20    37  70
21    65  78
22    65  93
23    61  77
24    52  88
25    57  82
26    57  76
27    75  87
28    61  84
29    47  77
30    54  82
31    66  91
32    54  75
33    54  76
34    42  78
35    37  57
36    79  89
37    56  83
38    62  69
39    62  86
40    55  81
41    63  81
42    57  80
43    57  79
44    67  87
45    55  84
46    45  71
47    66  80
48    55  77
49    64  83
50    66  88>

In [20]:
scores = np.array(df['英語'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [23]:
scores_df = pd.DataFrame({'点数':scores},index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],name=' 生徒'))
scores_df

点数
 生徒    
A    42
B    69
C    56
D    41
E    57
F    48
G    65
H    49
I    65
J    58

In [24]:
sum(scores)/len(scores)

55.0

In [25]:
scores_df.mean()

点数    55.0
dtype: float64

In [27]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [33]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2 - 1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else:
    median = sorted_scores[(n+1)//2 - 1]
median

56.5

In [34]:
np.median(scores)

56.5

In [36]:
scores_df.median()

点数    56.5
dtype: float64

In [37]:
pd.Series([1,1,1,2,2,3]).mode()

0    1
dtype: int64

In [38]:
pd.Series([1,2,3,4,5]).mode()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [40]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [41]:
another_scores = [50,60,58,54,51,56,57,53,52,59]
another_mean = np.mean(another_scores)
another_deviation = another_scores - another_mean
another_deviation

array([-5.,  5.,  3., -1., -4.,  1.,  2., -2., -3.,  4.])

In [47]:
np.mean(deviation)

0.0

In [49]:
summary_df = scores_df.copy()
summary_df['偏差'] = deviation
summary_df

点数    偏差
 生徒          
A    42 -13.0
B    69  14.0
C    56   1.0
D    41 -14.0
E    57   2.0
F    48  -7.0
G    65  10.0
H    49  -6.0
I    65  10.0
J    58   3.0

In [50]:
summary_df.mean()

点数    55.0
偏差     0.0
dtype: float64

In [51]:
np.mean(deviation ** 2)

86.0

In [52]:
np.var((scores))

86.0

In [53]:
scores_df.var()

点数    95.556
dtype: float64

In [55]:
summary_df['偏差二乗'] = np.square(deviation)
summary_df

点数    偏差   偏差二乗
 生徒                 
A    42 -13.0  169.0
B    69  14.0  196.0
C    56   1.0    1.0
D    41 -14.0  196.0
E    57   2.0    4.0
F    48  -7.0   49.0
G    65  10.0  100.0
H    49  -6.0   36.0
I    65  10.0  100.0
J    58   3.0    9.0

In [56]:
summary_df.mean()

点数      55.0
偏差       0.0
偏差二乗    86.0
dtype: float64

In [60]:
np.sqrt(np.var(scores,ddof=0))

9.273618495495704